replicaCount: 1

image:
  repository: ghcr.io/jj8817/hello-world-flask
  tag: "{{ .Values.image.tag | default 'latest' }}"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
