replicaCount: 2

image:
  repository: ghcr.io/jj8817/hello-world-flask
  tag: "{{ .Values.image.tag | default 'prod' }}"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
